version: '2'

services:
  telegraf:
    image: telegraf
    container_name: telegraf
    ports:
      - 57000:57000
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./tmp/metrics.out:/tmp/metrics.out
    networks:
      - monitoring

  influxdb:
    image: influxdb:1.8.5
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=mdt
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring

volumes:
  influxdb-volume:
  grafana-volume:
    
networks:
  monitoring:
